#Used for only lcoal testing, not safe for Production

apiVersion: v1
kind: Pod
metadata:
  name: hostpath-example
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh", "-c", "ls /host; sleep 3600"]
    volumeMounts:
    - name: host-volume
      mountPath: /host
  volumes:
  - name: host-volume
    hostPath:
      path: /tmp
      type: Directory

