# This file is used for creating Deployment, that manages the pods.
# This file creates Deployment --> ReplicaSet --> Pods

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      tier: frontend

  
