# Pod is used for running single or multiple containers.
# This file is an example of a Pod that runs a single container.

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  serviceAccountName: nginx-sa
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
