apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-storage
provisioner: kubernetes.io/no-provisioner  
parameters:
  type: gp2
reclaimPolicy: Delete
volumeBindingMode: Immediate

