apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-path
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /nginx
        pathType: Prefix
        backend:
          service:
            name: nginx-service-loadbalancer
            port:
              number: 80

